Controllers/MyAccoutController.cs
using projectdbfirst.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projectdbfirst.Controllers
{
    [Authorize(Roles = "client")]
    public class MyAccoutController : Controller
    {
        QLBHmvcEntities db = new QLBHmvcEntities();
        // GET: MyAccout
        public ActionResult Index()
        {
            int id = (int)Session["UserId"];
            //int id = 2;
            var kh = db.KHs.FirstOrDefault(k => k.KHUserId == id);
            var user = db.Users.FirstOrDefault(u => u.UserId == id);
            if (kh == null || user == null)
            {
                return HttpNotFound(); // Xử lý khi không tìm thấy đối tượng KH hoặc User
            }

            var viewModel = new UserDetailsViewModel
            {
                Kh = kh,
                User = user
            };

            List<projectdbfirst.Models.HDBan> dsHDBan = db.HDBans.Where(m => m.MaKH == kh.MaKH).ToList();
            ViewBag.DanhSachHDBan = dsHDBan;

            return View(viewModel);
        }
        [HttpPost]
        public ActionResult UpdateUser(UserDetailsViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var utud = db.Users.FirstOrDefault(u => u.UserId == viewModel.User.UserId);

                if (utud != null)
                {
                    // Cập nhật thông tin từ ViewModel vào đối tượng KH và User tương ứng
                    utud.Username = viewModel.User.Username; // Ví dụ cập nhật thuộc tính Username
                    utud.Password = viewModel.User.Password;

                    // Cập nhật vào cơ sở dữ liệu
                    db.Users.Attach(utud);
                    db.Entry(utud).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index"); // Hoặc chuyển hướng đến trang khác sau khi cập nhật thành công
                }
            }

            return View("Index",viewModel); // Trả về View nếu có lỗi xảy ra hoặc dữ liệu không hợp lệ
        }

        [HttpPost]
        public ActionResult UpdateKH(UserDetailsViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var khtud = db.KHs.FirstOrDefault(k => k.KHUserId == viewModel.Kh.KHUserId);

                if (khtud != null)
                {
                    // Cập nhật thông tin từ ViewModel vào đối tượng KH và User tương ứng
                    khtud.FullName = viewModel.Kh.FullName;
                    khtud.DiaChi = viewModel.Kh.DiaChi;
                    khtud.DienThoai = viewModel.Kh.DienThoai;
                    khtud.Email = viewModel.Kh.Email;

                    // Cập nhật vào cơ sở dữ liệu
                    db.KHs.Attach(khtud);
                    db.Entry(khtud).State = EntityState.Modified;
                    db.SaveChanges();

                    return RedirectToAction("Index"); // Hoặc chuyển hướng đến trang khác sau khi cập nhật thành công
                }
            }

            return View("Index",viewModel); // Trả về View nếu có lỗi xảy ra hoặc dữ liệu không hợp lệ
        }

        public ActionResult DetailsCTHDBan(int id)
        {
            var All = db.CTHDBans.Include(c => c.Hang).Include(c => c.HDBan);
            var cTHDBans = All.ToList();
            if (id != 0)
            {
                cTHDBans = cTHDBans.Where(c => c.MaHDBan == id).ToList();
            }
            return View(cTHDBans.ToList());
        }
    }
}

Views/MyAccout/DetailsCTHDBan.cshtml
@model IEnumerable<projectdbfirst.Models.CTHDBan>

@{
    ViewBag.Title = "DetailsCTHDBan";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!--breadcrumbs area start-->
<div class="breadcrumbs_area">
    <div class="row">
        <div class="col-12">
            <div class="breadcrumb_content">
                <ul>
                    <li><a href="@Url.Action("Index", "Home")">home</a></li>
                    <li><i class="fa fa-angle-right"></i></li>
                    <li>Details</li>
                </ul>

            </div>
        </div>
    </div>
</div>
<!--breadcrumbs area end-->
<table class="table">
    <thead>
        <tr style="text-align: center;">
            <th>Order</th>
            <th>Name</th>
            <th>Quantity</th>
            <th>price</th>
            <th>Amount</th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 0;
            foreach (var item in Model)
            {
                i = i + 1;
                <tr style="text-align: center">
                    <td>@i</td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Hang.TenH)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SoLuong)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DonGia)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ThanhTien)
                    </td>
                </tr>
            }
        }

    </tbody>
</table>

Views/MyAccout/Index.cshtml
@model projectdbfirst.Models.UserDetailsViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<head>
    <style>
        .local-btn {
            width: 60px;
            color: #000;
            border-radius: 5px;
            font-weight: bold;
        }
        .local-btn:hover {
            color: #fff;
            background-color: #00BBA6;
        }
    </style>
</head>
<p>
    @*@Html.ActionLink("Edit", "Index", new { id = Model.MaKH }) |
    @Html.ActionLink("Back to List", "Index")*@
</p>

<!--breadcrumbs area start-->
<div class="breadcrumbs_area">
    <div class="row">
        <div class="col-12">
            <div class="breadcrumb_content">
                <ul>
                    <li><a href="@Url.Action("Index", "Home")">home</a></li>
                    <li><i class="fa fa-angle-right"></i></li>
                    <li>my account</li>
                </ul>

            </div>
        </div>
    </div>
</div>
<!--breadcrumbs area end-->
<!-- Start Maincontent  -->
<section class="main_content_area">
    <div class="account_dashboard">
        <div class="row">
            <div class="col-sm-12 col-md-3 col-lg-3">
                <!-- Nav tabs -->
                <div class="dashboard_tab_button">
                    <ul role="tablist" class="nav flex-column dashboard-list">
                        <li><a href="#dashboard" data-toggle="tab" class="nav-link active">Dashboard</a></li>
                        <li> <a href="#orders" data-toggle="tab" class="nav-link">Orders</a></li>
                        <li><a href="#downloads" data-toggle="tab" class="nav-link">Account details</a></li>
                        <li><a href="#account-details" data-toggle="tab" class="nav-link">Profile</a></li>
                        <li><a href="@Url.Action("Logout","Account")" class="nav-link">logout</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-12 col-md-9 col-lg-9">
                <!-- Tab panes -->
                <div class="tab-content dashboard_content">
                    <div class="tab-pane fade show active" id="dashboard">
                        <h3>Dashboard </h3>
                        <p>From your account dashboard. you can easily check &amp; view your <a href="#">recent orders</a>, manage your <a href="#">shipping and billing addresses</a> and <a href="#">Edit your password and account details.</a></p>
                    </div>
                    <div class="tab-pane fade" id="orders">
                        <h3>Orders</h3>
                        <div class="coron_table table-responsive">
                            <table class="table">
                                <thead>
                                    <tr style="text-align: center;">
                                        <th>Order</th>
                                        <th>Date</th>
                                        <th>Total</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{
                                        if (ViewBag.DanhSachHDBan != null)
                                        {
                                            int i = 0;
                                            foreach (var hdBan in ViewBag.DanhSachHDBan)
                                            {
                                                i = i + 1;
                                                <tr>
                                                    <td>@i</td>
                                                    <td>@hdBan.NgayBan</td>
                                                    <td>@hdBan.TongTien</td>
                                                    <td><a href="@Url.Action("DetailsCTHDBan", "MyAccout", new { id = hdBan.MaHDBan})" class="view">view</a></td>
                                                </tr>
                                            }
                                        }
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="downloads">
                        <h3>Account detail </h3>
                        <div class="coron_table table-responsive">
                            <div class="account_login_form">
                                @using (Html.BeginForm("UpdateUser", "MyAccout", FormMethod.Post))
                                {
                                    @Html.HiddenFor(model => model.User.UserId)
                                    <label>UserName</label>
                                    @Html.EditorFor(model => model.User.Username)
                                    <label>PassWord</label>
                                    @Html.EditorFor(model => model.User.Password)
                                    @Html.HiddenFor(model => model.User.Role)
                                    @Html.HiddenFor(model => model.Kh.MaKH)
                                    @Html.HiddenFor(model => model.Kh.FullName)
                                    @Html.HiddenFor(model => model.Kh.DiaChi)
                                    @Html.HiddenFor(model => model.Kh.DienThoai)
                                    @Html.HiddenFor(model => model.Kh.Email)
                                    @Html.HiddenFor(model => model.Kh.KHUserId)
                                    <div class="save_button primary_btn default_button">
                                        <input type="submit" value="Save" class="btn local-btn" />
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="account-details">
                        <h3>Profile </h3>
                        <div class="login">
                            <div class="login_form_container">
                                <div class="account_login_form">
                                    @using (Html.BeginForm("UpdateKH", "MyAccout", FormMethod.Post))
                                    {
                                        @Html.HiddenFor(model => model.User.UserId)
                                        @Html.HiddenFor(model => model.User.UserId)
                                        @Html.HiddenFor(model => model.User.UserId)
                                        @Html.HiddenFor(model => model.User.Role)
                                        @Html.HiddenFor(model => model.Kh.MaKH)
                                        <label>Full Name</label>
                                        @Html.EditorFor(model => model.Kh.FullName)
                                        <label>Address</label>
                                        @Html.EditorFor(model => model.Kh.DiaChi)
                                        <label>Phone number</label>
                                        @Html.EditorFor(model => model.Kh.DienThoai)
                                        <label>Email</label>
                                        @Html.EditorFor(model => model.Kh.Email)
                                        @Html.HiddenFor(model => model.Kh.KHUserId)
                                        <div class="save_button primary_btn default_button">
                                            <input type="submit" value="Save" class="btn local-btn" />
                                        </div>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Maincontent  -->