Models/Hang.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectdbfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hang()
        {
            this.CTHDBans = new HashSet<CTHDBan>();
            this.CTHDNhaps = new HashSet<CTHDNhap>();
        }
    
        public int MaH { get; set; }
        public string TenH { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string MoTa { get; set; }
        public string Anh { get; set; }
        public Nullable<int> MaDanhMuc { get; set; }
        public Nullable<double> GiaTien { get; set; }
        public Nullable<int> GiamGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDBan> CTHDBans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHDNhap> CTHDNhaps { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
    }
}

Areas/Admin/Controllers/HangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using projectdbfirst.Models;
using PagedList;
using System.Text.RegularExpressions;
using static projectdbfirst.Controllers.HomeController;

namespace projectdbfirst.Areas.Admin.Controllers
{
    //[Authorize(Roles = "admin")]
    public class HangsController : Controller
    {
        private QLBHmvcEntities db = new QLBHmvcEntities();

        public ActionResult Index(int? page, int? Id)
        {
            if (TempData["SuccessMessageHang"] != null)
            {
                ViewBag.SuccessMessage = TempData["SuccessMessageHang"].ToString();
            }
            if (TempData["ErrorMessageHang"] != null)
            {
                ViewBag.ErrorMessage = TempData["ErrorMessageHang"].ToString();
            }

            var All = db.Hangs.Include(h => h.DanhMuc);
            var hangs = All.ToList();
            
            if ( Id != 0 )
            {
                hangs = hangs.Where(h => h.MaDanhMuc == Id).ToList(); 
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            IPagedList<Hang> pageHang = hangs.ToPagedList(pageNumber, pageSize);
            ViewBag.DanhMucHienTai = Id;
            return View(pageHang);
        }
        [HttpPost]
        public ActionResult Index(string search, int? page, int? Id)
        {
            var All = db.Hangs.Include(h => h.DanhMuc);
            var hangs = All.ToList();
            if (!string.IsNullOrEmpty(search))
            {
                search = RemoveSpecialCharacters(search);

                // Lọc danh sách theo chuỗi search đã được làm sạch
                hangs = hangs.Where(m => m.TenH.Contains(search)).ToList();
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            IPagedList<Hang> pageHang = hangs.ToPagedList(pageNumber, pageSize);
            ViewBag.DanhMucHienTai = Id;
            return View(pageHang);
        }

        public string RemoveSpecialCharacters(string input)
        {
            if (string.IsNullOrEmpty(input))
                return input;

            // Loại bỏ ký tự đặc biệt (chỉ giữ lại chữ cái, chữ số và khoảng trắng)
            string pattern = @"[^a-zA-Z0-9\s]";
            return Regex.Replace(input, pattern, string.Empty);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hang hang = db.Hangs.Find(id);
            if (hang == null)
            {
                return HttpNotFound();
            }

            var chats = db.Chats.Where(c => c.MaH == id).ToList();
            var chatTree = BuildChatTree(chats);

            ViewBag.ChatTree = chatTree;

            return View(hang);
        }

        public ActionResult Create(int ?id)
        {
            ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "Id", "Ten", id);
            ViewBag.MaDanhMucHienTai = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(Hang hang)
        {
            if (ModelState.IsValid)
            {
                var f = Request.Files["fAvatar"];
                if (f != null && f.ContentLength > 0)
                {
                    string folderName = Server.MapPath("~/Assets/Uploads");
                    string fileName = f.FileName;
                    f.SaveAs(folderName + "/" + fileName);
                    hang.Anh = "/Assets/Uploads/" + fileName;
                }
                db.Hangs.Add(hang);
                db.SaveChanges();
                return RedirectToAction("Index", new { page = 1, id = hang.MaDanhMuc });
            }

            ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "Id", "Ten", hang.MaDanhMuc);
            return View(hang);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hang hang = db.Hangs.Find(id);
            if (hang == null)
            {
                return HttpNotFound();
            }
            string anhs = db.Hangs.Where(m => m.MaH == id).Select(c => c.Anh).FirstOrDefault();
            ViewBag.Anhs = anhs;
            ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "Id", "Ten", hang.MaDanhMuc);
            return View(hang);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(Hang hang)
        {
            if (ModelState.IsValid)
            {
                var f = Request.Files["fAvatar"];
                if (f != null && f.ContentLength > 0)
                {
                    string folderName = Server.MapPath("~/Assets/Uploads");
                    string fileName = f.FileName;
                    f.SaveAs(folderName + "/" + fileName);
                    hang.Anh = "/Assets/Uploads/" + fileName;
                }
                else
                {
                    var existingHang = db.Hangs.AsNoTracking().FirstOrDefault(m => m.MaH == hang.MaH);
                    hang.Anh = existingHang.Anh;
                }
                db.Entry(hang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { id = hang.MaDanhMuc });
            }
            ViewBag.MaDanhMuc = new SelectList(db.DanhMucs, "Id", "Ten", hang.MaDanhMuc);
            return View(hang);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Hang hang = db.Hangs.Find(id);
            if (hang == null)
            {
                return HttpNotFound();
            }
            return View(hang);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int? key)
        {
            var hang = db.Hangs.Find(id);
            if( hang == null)
            {
                return HttpNotFound();
            }
            var check = db.CTHDNhaps.Any(c => c.MaH == id);
            if( check )
            {
                TempData["ErrorMessageHang"] = "sản phẩm này hiện đang sử dụng ! không thể xóa!";
            }
            else
            {
                db.Hangs.Remove(hang);
                db.SaveChanges();
                TempData["SuccessMessageHang"] = "Thao tác đã hoàn thành thành công!";
            }
            //Hang hang = db.Hangs.Find(id);
            //db.Hangs.Remove(hang);
            //db.SaveChanges();
            return RedirectToAction("Index", new { Id = key });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        private List<ChatNode> BuildChatTree(List<Chat> chats)
        {
            var chatDict = new Dictionary<int, ChatNode>();
            var rootChats = new List<ChatNode>();

            // Tạo các đối tượng ChatNode và thêm vào từ điển
            foreach (var chat in chats)
            {
                var kh = db.KHs.FirstOrDefault(k => k.MaKH == chat.MaKH);
                var node = new ChatNode
                {
                    ChatId = chat.ChatId,
                    TenKH = kh?.FullName,
                    MaH = chat.MaH,
                    ParentChatId = chat.ParentChatId,
                    Content = chat.Content,
                    Time = chat.Time,
                    Children = new List<ChatNode>()
                };
                chatDict[chat.ChatId] = node;

                // Nếu ParentChatId là -1, thêm vào danh sách gốc
                if (chat.ParentChatId == -1)
                {
                    rootChats.Add(node);
                }
            }

            // Gắn các node con vào node cha
            foreach (var chat in chats)
            {
                if (chat.ParentChatId != -1)
                {
                    var parentId = chat.ParentChatId;
                    if (parentId.HasValue && chatDict.ContainsKey(parentId.Value))
                    {
                        chatDict[parentId.Value].Children.Add(chatDict[chat.ChatId]);
                    }
                }
            }

            // Hàm sắp xếp đệ quy cho cây chat
            void SortChatNodes(List<ChatNode> nodes)
            {
                nodes.Sort((x, y) => y.Time.GetValueOrDefault().CompareTo(x.Time.GetValueOrDefault()));
                foreach (var node in nodes)
                {
                    if (node.Children.Any())
                    {
                        SortChatNodes(node.Children);
                    }
                }
            }

            // Sắp xếp danh sách rootChats và các node con
            SortChatNodes(rootChats);

            return rootChats;
        }
    }
}

Areas/Admin/Views/Hangs/Create.cshtml
@model projectdbfirst.Models.Hang

@{
    ViewBag.Title = "Create";
}

<h2>Thêm mới sản phẩm</h2>


@using (Html.BeginForm("Create", "Hangs", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Hang</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.TenH, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenH, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaTien, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaTien, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaTien, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiamGia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="position: relative;">
            @Html.EditorFor(model => model.GiamGia, new
            {
                htmlAttributes = new
                {
                    @class = "form-control",
                    type = "number",
                    min = "0",
                    max = "50",
                    step = "1"
                }
            })
            <div style="display: inline-block; position: absolute; top: 8px; left: 31px;">%</div>
            @Html.ValidationMessageFor(model => model.GiamGia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.TextAreaFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Anh, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" class="btn btn-light" name="fAvatar" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaDanhMuc, "MaDanhMuc", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaDanhMuc", null, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
            @Html.ValidationMessageFor(model => model.MaDanhMuc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 mb-2 mt-2">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new {id = ViewBag.MaDanhMucHienTai }, new { @class = "btn btn-primary"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        CKEDITOR.replace("MoTa");
    </script>
}

Areas/Admin/Views/Hangs/Delete.cshtml
@model projectdbfirst.Models.Hang

@{
    ViewBag.Title = "Delete";
}
<style>
    .card-img-top {
        width: 240px;
        height: 100px;
        object-fit: cover;
    }
</style>
<h2>Xóa sản phẩm</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Hang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anh)
        </dt>

        <dd>
            <img src="@Model.Anh" alt="@Model.TenH" class="card-img-top" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DanhMuc.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DanhMuc.Ten)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index", new { id = Model.MaDanhMuc }, new { @class = "btn btn-primary"})
        </div>
    }
</div>

Areas/Admin/Views/Hangs/Details.cshtml
@model projectdbfirst.Models.Hang

@{
    ViewBag.Title = "Details";
    var chatTree = ViewBag.ChatTree as List<projectdbfirst.Controllers.HomeController.ChatNode>;
}
<style>
    .card-img-top {
        width: 240px;
        height: 100px;
        object-fit: cover;
    }

    .nodeUl > .chatContainer {
        font-size: 16px;
        padding: 10px 20px 20px 20px;
        margin-bottom: 10px;
    }

    .chatHead {
        display: block;
        font-size: 16px;
    }

    .nodeChat {
        padding: 12px 20px 12px 20px;
        border: 1px solid black;
        border-radius: 4px;
        margin: 12px 4px;
        background-color: #fff;
    }

    .btn {
        border: 0.5px solid #000;
        background-color: #eee;
        color: #000;
        border-radius: 4px;
        font-size: 18px;
        margin: 12px 4px 0 0;
    }

    .inputChat {
    }

    .chatTime {
        margin-left: 30px;
    }
    ul ,li {
        list-style-type: none;
    }
</style>

<h2>Chi tiết</h2>

<div>
    <h4>Hang</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SoLuong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoLuong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MoTa)
        </dt>

        <dd>
            @Html.Raw(Model.MoTa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anh)
        </dt>

        <dd>
            <img src="@Model.Anh" alt="@Model.TenH" class="card-img-top" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DanhMuc.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DanhMuc.Ten)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaH }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Back to List", "Index", new { id = Model.MaDanhMuc }, new { @class = "btn btn-primary" })
</p>


<div style="background-color: #FCFCFA; border-radius: 4px;">
    <h4 style="text-align: center; padding-top: 22px;">Chats</h4>
    @if (chatTree != null)
    {
        <ul class="nodeUl">
            @Html.Raw(RenderChatTree(chatTree))
        </ul>
    }
</div>
@functions {
    // Hàm đệ quy để hiển thị cây chat
    private string RenderChatTree(List<projectdbfirst.Controllers.HomeController.ChatNode> nodes, int level = 0)
    {
        var html = new System.Text.StringBuilder();

        foreach (var node in nodes)
        {
            // Tính toán khoảng thời gian
            TimeSpan timeAgo = (TimeSpan)(DateTime.Now - node.Time);
            string timeAgoString = FormatTimeAgo(timeAgo);

            // Gán vào node
            node.TimeAgo = timeAgoString;

            html.AppendFormat("<li class='chatContainer' style='margin-left:{0}px'>", level * 30);
            html.Append("<div class='nodeChat'>");
            html.AppendFormat("<div class='chatHead'><strong class=''>{0}</strong><span class='chatTime'>{1}</span></div> {2}", node.TenKH, node.TimeAgo, node.Content);
            html.Append("</div>");
            if (node.Children.Any())
            {
                html.Append("<ul class='chats'>");
                html.Append(RenderChatTree(node.Children, level + 1));
                html.Append("</ul>");
            }
            html.Append("</li>");
        }

        return html.ToString();
    }
    private string FormatTimeAgo(TimeSpan timeAgo)
    {
        if (timeAgo.TotalSeconds < 60)
            return "vừa xong";
        if (timeAgo.TotalMinutes < 60)
            return $"{(int)timeAgo.TotalMinutes} phút trước";
        if (timeAgo.TotalHours < 24)
            return $"{(int)timeAgo.TotalHours} giờ trước";
        if (timeAgo.TotalDays < 30)
            return $"{(int)timeAgo.TotalDays} ngày trước";
        return $"{(int)(timeAgo.TotalDays / 30)} tháng trước";
    }
}

Areas/Admin/Views/Hangs/Edit.cshtml
@model projectdbfirst.Models.Hang

@{
    ViewBag.Title = "Edit";
}

<h2>Sửa thông tin sản phẩm</h2>


@using (Html.BeginForm("Edit", "Hangs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Hang</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MaH)

    <div class="form-group">
        @Html.LabelFor(model => model.TenH, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenH, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.SoLuong, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaTien, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaTien, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaTien, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiamGia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10" style="position: relative;">
            @Html.EditorFor(model => model.GiamGia, new
            {
                htmlAttributes = new
                {
                    @class = "form-control",
                    type = "number",
                    min = "0",
                    max = "50",
                    step = "1"
                }
            })
            <div style="display: inline-block; position: absolute; top: 8px; left: 31px;">%</div>
            @Html.ValidationMessageFor(model => model.GiamGia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @*@Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })*@
            @Html.TextAreaFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Anh, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" class="btn btn-light" name="fAvatar" value="@ViewBag.Anhs" />
            <img src="@ViewBag.Anhs" alt="Ảnh hiện tại" width="200" height="200" style="margin: 0 30px;" />
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaDanhMuc, "MaDanhMuc", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaDanhMuc", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaDanhMuc, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 mb-2 mt-2">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = Model.MaDanhMuc }, new { @class = "btn btn-primary" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        CKEDITOR.replace("MoTa");
    </script>
}

Areas/Admin/Views/Hangs/Index.cshtml
@model IPagedList<projectdbfirst.Models.Hang>
@using PagedList;
@using PagedList.Mvc;
@*@model IEnumerable<projectdbfirst.Models.Hang>*@

@{
    ViewBag.Title = "Index";
}
<style>
    .card-img-top {
        width: 100px;
        height: 100px;
        object-fit: cover;
    }
</style>

<h2>Danh sách sản phẩm</h2>
@if (!string.IsNullOrEmpty(ViewBag.SuccessMessage))
{
    <div class="alert alert-success alert-dismissible">
        @ViewBag.SuccessMessage
        <button type="button" class="close btn-close" data-dismiss="alert" aria-label="Close">
        </button>
    </div>
}
@if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
{
    <div class="alert alert-danger alert-dismissible">
        @ViewBag.ErrorMessage
        <button type="button" class="close btn-close" data-dismiss="alert" aria-label="Close">
        </button>
    </div>
}
<p>
    @Html.ActionLink("Create New", "Create", new { id = ViewBag.DanhMucHienTai }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("Danh mục", "Index", "DanhMucs", new { area = "Admin" }, new { @class = "btn btn-primary" }) |
    @Html.ActionLink("danh sách tổng", "Index", new { id = 0 }, new { @class = "btn btn-primary" })
</p>
@using (Html.BeginForm("Index","Hangs", new { area = "Admin" }, FormMethod.Post, new { id = ViewBag.DanhMucHienTai }))
{
    <div class="input-group" style="width: 300px; transform: translateX(300%); margin: 20px 0;">
        <input type="search" class="form-control" placeholder="Search name" id="search" name="search" />
        <button type="submit" class="btn btn-outline-primary">search</button>
    </div>
}
<table class="table">
    <tr>
        <th>
            Mã hàng
        </th>
        <th>
            Tên hàng
        </th>
        <th>
            Số lượng
        </th>
        <th>
            Giá tiền
        </th>
        <th>
            Giảm giá
        </th>
        <th>
            Ảnh
        </th>
        <th>
            Tên danh mục
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaTien)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiamGia) %
            </td>
            <td>
                <img src="@item.Anh" alt="@item.TenH" class="card-img-top" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DanhMuc.Ten)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MaH }, new { @class = "btn btn-primary" }) |
                @Html.ActionLink("Details", "Details", new { id = item.MaH }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MaH, key = ViewBag.DanhMucHienTai }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>
<div class="pagination-container">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, id = ViewBag.DanhMucHienTai }))
</div>