Areas/Admin/Controllers/ChartController.cs
using projectdbfirst.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace projectdbfirst.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class ChartController : Controller
    {
        private QLBHmvcEntities db = new QLBHmvcEntities();
        // GET: Admin/Chart
        public ActionResult Index()
        {
            var ordersData = db.HDNhaps
            .Select(o => new
            {
                Type = "HDNhaps",
                Month = o.NgayNhap.HasValue ? o.NgayNhap.Value.Month : 0,
                Year = o.NgayNhap.HasValue ? o.NgayNhap.Value.Year : 0,
                Amount = o.TongTien
            });

            var importsData = db.HDBans
                .Select(n => new
                {
                    Type = "HDBans",
                    Month = n.NgayBan.HasValue ? n.NgayBan.Value.Month : 0,
                    Year = n.NgayBan.HasValue ? n.NgayBan.Value.Year : 0,
                    Amount = n.TongTien
                });

            var allData = ordersData.Concat(importsData)
                .GroupBy(d => new { d.Month, d.Year })
                .Select(g => new
                {
                    Month = g.Key.Month,
                    Year = g.Key.Year,
                    ImportAmount = g.FirstOrDefault(d => d.Type == "HDNhaps") != null ? g.FirstOrDefault(d => d.Type == "HDNhaps").Amount : 0,
                    OrderAmount = g.FirstOrDefault(d => d.Type == "HDBans") != null ? g.FirstOrDefault(d => d.Type == "HDBans").Amount : 0
                })
                .OrderBy(g => g.Year)
                .ThenBy(g => g.Month)
                .ToList();

            var labels = allData.Select(m => $"{m.Month}/{m.Year}").ToArray();
            var orderData = allData.Select(m => m.OrderAmount).ToArray();
            var importData = allData.Select(m => m.ImportAmount).ToArray();

            ViewBag.Labels = labels;
            ViewBag.OrderData = orderData;
            ViewBag.ImportData = importData;

            return View();
        }
        public ActionResult RemainingChart()
        {
            var productsData = db.Hangs
                .Select(h => new {
                    ProductName = h.TenH,
                    RemainingQuantity = h.SoLuong
                })
                .ToList();

            if (productsData != null && productsData.Any())
            {
                ViewBag.ProductsData = productsData;
            }
            else
            {
                ViewBag.ProductsData = new List<object>(); 
            }

            return View();
        }

        [HttpGet]
        public ActionResult ImportChart(int? thang, int? nam)
        {
            if(thang.HasValue && nam.HasValue)
            {
                // xác định các hóa đơn có tháng và năm
                List<Models.HDNhap> hdNhapData = db.HDNhaps.Where(c => c.NgayNhap.Value.Month == thang && c.NgayNhap.Value.Year == nam).ToList();

                // Dictionary để lưu trữ số lượng hàng nhập của từng sản phẩm
                Dictionary<string, int> productQuantities = new Dictionary<string, int>();

                // Lặp qua các hóa đơn và lấy các chi tiết hóa đơn kết nối với hóa đơn đó
                foreach(var hdNhap in hdNhapData)
                {
                    var ctHDNhapData = db.CTHDNhaps.Where(m => m.MaHDNhap == hdNhap.MaHDNhap).ToList();

                    // Tính tổng số lượng hàng nhập của từng sản phẩ
                    foreach(var cthdNhap in ctHDNhapData)
                    {
                        //string key = cthdNhap.MaH.ToString();
                        string key = db.Hangs.FirstOrDefault(m => m.MaH == cthdNhap.MaH)?.TenH;
                        if (productQuantities.ContainsKey(key))
                        {
                            productQuantities[key] += cthdNhap.SoLuong ?? 0;
                        }
                        else
                        {
                            productQuantities[key] = cthdNhap.SoLuong ?? 0;
                        }
                    }
                }
                // Chuyển dữ liệu từ Dictionary sang các mảng để sử dụng trong biểu đồ
                var productNames = productQuantities.Keys.ToArray();
                var remainingQuantities = productQuantities.Values.ToArray();

                //ViewBag.ProductNames = productNames;
                //ViewBag.RemainingQuantities = remainingQuantities;
                return Json(new { ProductNames = productNames, RemainingQuantities = remainingQuantities }, JsonRequestBehavior.AllowGet);
            }
            return View();
        }

        [HttpGet]
        public ActionResult OrderChart(int? thang, int? nam)
        {
            if (thang.HasValue && nam.HasValue)
            {
                // xác định các hóa đơn có tháng và năm
                List<Models.HDBan> hdBanData = db.HDBans.Where(c => c.NgayBan.Value.Month == thang && c.NgayBan.Value.Year == nam).ToList();

                // Dictionary để lưu trữ số lượng hàng nhập của từng sản phẩm
                Dictionary<string, int> productQuantities = new Dictionary<string, int>();

                // Lặp qua các hóa đơn và lấy các chi tiết hóa đơn kết nối với hóa đơn đó
                foreach (var hdBan in hdBanData)
                {
                    var ctHDBanData = db.CTHDBans.Where(m => m.MaHDBan == hdBan.MaHDBan).ToList();

                    // Tính tổng số lượng hàng nhập của từng sản phẩ
                    foreach (var cthdBan in ctHDBanData)
                    {
                        //string key = cthdNhap.MaH.ToString();
                        string key = db.Hangs.FirstOrDefault(m => m.MaH == cthdBan.MaH)?.TenH;
                        if (productQuantities.ContainsKey(key))
                        {
                            productQuantities[key] += cthdBan.SoLuong ?? 0;
                        }
                        else
                        {
                            productQuantities[key] = cthdBan.SoLuong ?? 0;
                        }
                    }
                }
                // Chuyển dữ liệu từ Dictionary sang các mảng để sử dụng trong biểu đồ
                var productNames = productQuantities.Keys.ToArray();
                var remainingQuantities = productQuantities.Values.ToArray();

                //ViewBag.ProductNames = productNames;
                //ViewBag.RemainingQuantities = remainingQuantities;
                return Json(new { ProductNames = productNames, RemainingQuantities = remainingQuantities }, JsonRequestBehavior.AllowGet);
            }
            return View();
        }
    }
}

Areas/Admin/Views/Chart/ImportChart.cshtml
@{
    ViewBag.Title = "ImportChart";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center">ImportChart</h2>
<a class="btn btn-primary mb-2" href="#" onclick="window.print(); return false;">Print</a>

@using (Html.BeginForm("ImportChart", "Chart", FormMethod.Get, new { id = "chartForm" }))
{
    <label for="thang">Tháng:</label>
    <select name="thang" id="thang" required style="width: 70px; padding: 4px; border-radius: 20px;">
        @for (int i = 1; i <= 12; i++)
        {
            <option value="@i">@i</option>
        }
    </select>

    <label for="nam">Năm:</label>
    <select name="nam" id="nam" required style="width: 100px; padding: 4px; border-radius: 20px;">
        @for (int i = DateTime.Now.Year; i >= 2000; i--)
        {
            <option value="@i">@i</option>
        }
    </select>

    <button type="submit" style="color: #696cff;
                                border-color: #696cff;
                                background: transparent;
                                outline: none;
                                padding: 4px 12px;
                                border-radius: 17px;
                                margin-left: 16px; ">
        Search
    </button>
}
<div id="parentChart">
    <canvas id="chartProduct"></canvas>
</div>

@section scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/Assets/Chart/Chart.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#chartForm').submit(function (event) {
                event.preventDefault(); // Ngăn chặn việc gửi form một cách thông thường
                var formData = $(this).serialize(); // Lấy dữ liệu từ form

                $.ajax({
                    url: '@Url.Action("ImportChart", "Chart")',
                    type: 'GET',
                    data: formData,
                    success: function (result) {
                        var productNames = result.ProductNames;
                        var remainingQuantities = result.RemainingQuantities;
                        replaceChart();
                        var ctx = document.getElementById('chartProduct');
                        var barChartData = {
                            labels: productNames,
                            datasets: [{
                                label: 'Import',
                                borderWidth: 1,
                                backgroundColor: '#CD3131',
                                data: remainingQuantities
                            }]
                        };

                        // Xóa biểu đồ cũ trước khi vẽ biểu đồ mới
                        //if (window.myBarChart != undefined)
                        //    window.myBarChart.destroy();

                        var myBarChart = new Chart(ctx, {
                            type: 'bar',
                            data: barChartData
                        });
                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            });
        });

        function replaceChart() {
            var canvas = document.getElementById('chartProduct');

            canvas.parentNode.removeChild(canvas);

            var newCanvas = document.createElement('canvas');
            newCanvas.id = 'chartProduct';

            var parent = document.getElementById('parentChart');
            parent.appendChild(newCanvas);
        }
    </script>
}

Areas/Admin/Views/Chart/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center">Chart</h2>
<a class="btn btn-primary" href="#" onclick="window.print(); return false;">Print</a>

<div>
    <canvas id="chartProduct"></canvas>
</div>

@section scripts {
    <script src="~/Assets/Chart/Chart.min.js"></script>
    <script>
        var ctx = document.getElementById('chartProduct');
        var barChartData = {
            labels: @Html.Raw(Json.Encode(ViewBag.Labels)),
            datasets: [{
                label: 'Order',
                borderWidth: 1,
                backgroundColor: '#66C732',
                data: @Html.Raw(Json.Encode(ViewBag.OrderData))
            }, {
                label: 'Import',
                borderWidth: 1,
                backgroundColor: '#CD3131',
                data: @Html.Raw(Json.Encode(ViewBag.ImportData))
            }]
        };
        var myBarChart = new Chart(ctx, {
            type: 'bar',
            data: barChartData
        })
    </script>
}

Areas/Admin/Views/Chart/OrderChart.cshtml
@{
    ViewBag.Title = "OrderChart";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center">OrderChart</h2>
<a class="btn btn-primary mb-2" href="#" onclick="window.print(); return false;">Print</a>

@using (Html.BeginForm("OrderChart", "Chart", FormMethod.Get, new { id = "chartForm" }))
{
    <label for="thang">Tháng:</label>
    <select name="thang" id="thang" required style="width: 70px; padding: 4px; border-radius: 20px;">
        @for (int i = 1; i <= 12; i++)
        {
            <option value="@i">@i</option>
        }
    </select>

    <label for="nam">Năm:</label>
    <select name="nam" id="nam" required style="width: 100px; padding: 4px; border-radius: 20px;">
        @for (int i = DateTime.Now.Year; i >= 2000; i--)
        {
            <option value="@i">@i</option>
        }
    </select>

    <button type="submit" style="color: #696cff;
         border-color: #696cff;
         background: transparent;
         outline: none;
         padding: 4px 12px;
         border-radius: 17px;
         margin-left: 16px; ">
        Search
    </button>
}
<div id="parentChart">
    <canvas id="chartProduct"></canvas>
</div>

@section scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/Assets/Chart/Chart.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#chartForm').submit(function (event) {
                event.preventDefault(); // Ngăn chặn việc gửi form một cách thông thường
                var formData = $(this).serialize(); // Lấy dữ liệu từ form

                $.ajax({
                    url: '@Url.Action("OrderChart", "Chart")',
                    type: 'GET',
                    data: formData,
                    success: function (result) {
                        var productNames = result.ProductNames;
                        var remainingQuantities = result.RemainingQuantities;
                        replaceChart();
                        var ctx = document.getElementById('chartProduct');
                        var barChartData = {
                            labels: productNames,
                            datasets: [{
                                label: 'Order',
                                borderWidth: 1,
                                backgroundColor: '#66C732',
                                data: remainingQuantities
                            }]
                        };

                        // Xóa biểu đồ cũ trước khi vẽ biểu đồ mới
                        //if (window.myBarChart != undefined)
                        //    window.myBarChart.destroy();

                        var myBarChart = new Chart(ctx, {
                            type: 'bar',
                            data: barChartData
                        });
                    },
                    error: function (error) {
                        console.log(error);
                    }
                });
            });
        });
        function replaceChart() {
            var canvas = document.getElementById('chartProduct');

            canvas.parentNode.removeChild(canvas);

            var newCanvas = document.createElement('canvas');
            newCanvas.id = 'chartProduct';

            var parent = document.getElementById('parentChart');
            parent.appendChild(newCanvas);
        }
    </script>
}

Areas/Admin/Views/Chart/RemainingChart.cshtml
@{
    ViewBag.Title = "RemainingChart";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    //var productsData = ViewBag.ProductsData as IEnumerable<dynamic>;
}

<h2 class="text-center">RemainingChart</h2>
<a class="btn btn-primary" href="#" onclick="window.print(); return false;">Print</a>
<a class="btn btn-primary" href="#" return false;">Xuât ra Excel</a>

<div>
    <canvas id="chartProduct"></canvas>
</div>

@section scripts{
    <script src="~/Assets/Chart/Chart.min.js"></script>
    <script>
        var ctxNew = document.getElementById('chartProduct');
        var productsData = @Html.Raw(Json.Encode(ViewBag.ProductsData));
        var productNames = [];
        var remainingQuantities = [];

        if (productsData !== null && productsData.length > 0) {
            for (var i = 0; i < productsData.length; i++) {
                productNames.push(productsData[i].ProductName);
                remainingQuantities.push(productsData[i].RemainingQuantity);
            }
        }

        var newChartProduct = new Chart(ctxNew, {
            type: 'bar',
            data: {
                labels: productNames,
                datasets: [{
                    label: 'Số lượng còn lại',
                    borderWidth: 1,
                    backgroundColor: '#FF6384',
                    data: remainingQuantities
                }]
            }
        });
    </script>
}