Models/KH.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectdbfirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KH()
        {
            this.HDBans = new HashSet<HDBan>();
        }
    
        public int MaKH { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public Nullable<int> KHUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HDBan> HDBans { get; set; }
    }
}

Areas/Admin/Controllers/KHsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using projectdbfirst.Models;
using PagedList;
using System.Drawing.Printing;

namespace projectdbfirst.Areas.Admin.Controllers
{
    [Authorize(Roles = "admin")]
    public class KHsController : Controller
    {
        private QLBHmvcEntities db = new QLBHmvcEntities();

        public ActionResult Index(int? page, int? pSize)
        {
            ViewBag.Print = false;
            int ps = 5;
            if (pSize != null)
            {
                ps = db.KHs.Count();
                ViewBag.Print = true;
            }
            var ketQua = (from kh in db.KHs
                          from user in db.Users
                          where kh.KHUserId == user.UserId
                          select new KHUserViewModel
                          {
                              KHInfo = kh,
                              UserInfo = user
                          }).ToList();

            int pageSize = ps; 
            int pageNumber = (page ?? 1); 

            IPagedList<KHUserViewModel> pagedResult = ketQua.ToPagedList(pageNumber, pageSize);

            return View(pagedResult);
        }

        public ActionResult Create(int id)
        {
            ViewBag.Id = id;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(KH kH)
        {
            if (ModelState.IsValid)
            {
                db.KHs.Add(kH);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(kH);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var khUserViewModel = GetKHUserViewModelById(id);
            if (khUserViewModel == null)
            {
                return HttpNotFound();
            }
            return View(khUserViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(projectdbfirst.Models.KHUserViewModel khUserViewModel)
        {
            if (ModelState.IsValid)
            {
                var khToEdit = db.KHs.FirstOrDefault(c => c.KHUserId == khUserViewModel.KHInfo.KHUserId);

                // Kiểm tra xem đối tượng KH có tồn tại hay không
                if (khToEdit == null)
                {
                    return HttpNotFound();
                }

                // Cập nhật thông tin cho đối tượng KH từ KHUserViewModel
                khToEdit.FullName = khUserViewModel.KHInfo.FullName;
                khToEdit.DiaChi = khUserViewModel.KHInfo.DiaChi;
                khToEdit.DienThoai = khUserViewModel.KHInfo.DienThoai;
                khToEdit.Email = khUserViewModel.KHInfo.Email;

                db.Entry(khToEdit).State = EntityState.Modified;
                // Lưu thay đổi vào cơ sở dữ liệu
                db.SaveChanges();
                //db.Entry(kH).State = EntityState.Modified;
                //db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(khUserViewModel);
        }

        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    KH kH = db.KHs.Find(id);
        //    if (kH == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(kH);
        //}

        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    KH kH = db.KHs.Find(id);
        //    db.KHs.Remove(kH);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        private KHUserViewModel GetKHUserViewModelById(int? id)
        {
            if (id == null)
            {
                return null;
            }

            // Lấy thông tin KH và User từ id
            var kh = db.KHs.Find(id);
            var user = db.Users.FirstOrDefault(u => u.UserId == kh.KHUserId);

            if (kh == null || user == null)
            {
                return null;
            }

            // Tạo một đối tượng KHUserViewModel và gán giá trị từ KH và User
            var khUserViewModel = new KHUserViewModel
            {
                KHInfo = kh,
                UserInfo = user,
            };

            return khUserViewModel;
        }
    }
}

Areas/Admin/Views/KHs/Create.cshtml
@model projectdbfirst.Models.KH

@{
    ViewBag.Title = "Create";
}

<h2>Thêm mới khách hàng</h2>


@using (Html.BeginForm("Create","KHs")) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>KH</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DienThoai, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.KHUserId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KHUserId, new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.Id, @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.KHUserId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 mb-2 mt-2">
            <input type="submit" value="Create" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Admin/Views/KHs/Delete.cshtml
@model projectdbfirst.Models.KH

@{
    ViewBag.Title = "Delete";
}

<h2>Xóa thông tin khách hàng</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>KH</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DienThoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DienThoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary"})
        </div>
    }
</div>

Areas/Admin/Views/KHs/Edit.cshtml
@model projectdbfirst.Models.KHUserViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Chi tiết thông tin khách hàng</h2>


@using (Html.BeginForm("Edit","Khs"))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>KH</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.KHInfo.MaKH)
    @Html.HiddenFor(model => model.UserInfo.UserId)
    @Html.HiddenFor(model => model.UserInfo.Username)
    @Html.HiddenFor(model => model.UserInfo.Password)
    @Html.HiddenFor(model => model.UserInfo.Role)
    @Html.HiddenFor(model => model.KHInfo.KHUserId)

    <div class="form-group">
        @Html.LabelFor(model => model.KHInfo.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KHInfo.FullName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KHInfo.FullName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KHInfo.DiaChi, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KHInfo.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KHInfo.DiaChi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KHInfo.DienThoai, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KHInfo.DienThoai, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KHInfo.DienThoai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.KHInfo.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KHInfo.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KHInfo.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 mb-2 mt-2">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Areas/Admin/Views/KHs/Index.cshtml
@model IPagedList<projectdbfirst.Models.KHUserViewModel>
@using PagedList;
@using PagedList.Mvc;

@*@model IEnumerable<projectdbfirst.Models.KHUserViewModel>*@

@{
    ViewBag.Title = "Index";
}


@if (ViewBag.Print)
{
    <h2 class="text-center">Danh sách Khách hàng</h2>
    @Html.ActionLink("Back", "Index", new { page = 1 }, new { @class = "btn btn-success", style = "margin-left: 8px;" })
    <a class="btn btn-primary" style="margin-left: 8px;" href="#" onclick="window.print(); return false;">Print</a>
    <table class="table">
        <tr>
            <th>
                Mã khách hàng
            </th>
            <th>
                Tên đầy đủ
            </th>
            <th>
                Địa chỉ
            </th>
            <th>
                Điện thoại
            </th>
            <th>
                Email
            </th>
            <th>
                UserName
            </th>
            <th>
                PassWord
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.KHInfo.MaKH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KHInfo.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KHInfo.DiaChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KHInfo.DienThoai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KHInfo.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserInfo.Username)
                </td>
                <td>
                    ********
                </td>
                @Html.HiddenFor(modelItem => item.KHInfo.KHUserId)
            </tr>
        }

    </table>
}
else
{
    <h2>Danh sách khách hàng</h2>
    @Html.ActionLink("Print list", "Index", new { page = 1, pSize = 0 }, new { @class = "btn btn-success" })
    <table class="table">
        <tr>
            <th>
                Mã khách hàng
            </th>
            <th>
                Tên đầy đủ
            </th>
            <th>
                Địa chỉ
            </th>
            <th>
                Điện thoại
            </th>
            <th>
                Email
            </th>
            <th>
                UserName
            </th>
            <th>
                PassWord
            </th>
            @*<th>
                    KHUserID
                </th>*@
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.KHInfo.MaKH)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KHInfo.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KHInfo.DiaChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KHInfo.DienThoai)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.KHInfo.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserInfo.Username)
                </td>
                <td>
                    ********
                </td>
                <td>

                    @Html.ActionLink("Edit", "Edit", new { id = item.KHInfo.MaKH }, new { @class = "btn btn-primary" })
                </td>
                @Html.HiddenFor(modelItem => item.KHInfo.KHUserId)
            </tr>
        }

    </table>
}
@*<p>
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary"})
    </p>*@

<div class="pagination-container">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>